# Generated by Django 5.1.3 on 2024-11-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toDos', '0002_todo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
