# Generated by Django 5.1.3 on 2024-11-25 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toDos', '0003_alter_todo_creation_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='to_dos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SubToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('text', models.TextField()),
                ('complition', models.BooleanField()),
                ('to_do', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='toDos.todo')),
            ],
        ),
    ]
