# Generated by Django 5.1.3 on 2024-11-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toDos', '0006_alter_todo_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='complition_date',
            field=models.DateTimeField(null=True),
        ),
    ]
