# Generated by Django 5.1.3 on 2024-11-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toDos', '0008_alter_todo_complition_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtodo',
            name='text',
            field=models.TextField(max_length=450),
        ),
    ]
