# Generated by Django 5.1.3 on 2024-12-03 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toDos', '0010_alter_subtodo_to_do_alter_todo_complition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtodo',
            name='to_do',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='toDos.todo'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='image',
            field=models.ImageField(blank='True', null=True, upload_to='images/'),
        ),
    ]
