# Generated by Django 5.1.3 on 2024-12-08 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toDos', '0013_alter_subtodo_complition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtodo',
            old_name='complition',
            new_name='completion',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='complition',
            new_name='completion',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='complition_date',
            new_name='completion_date',
        ),
    ]
