# Generated by Django 5.1.3 on 2024-12-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toDos', '0016_remove_userrewards_image_userrewards_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrewards',
            name='image_url',
            field=models.URLField(),
        ),
    ]
