# Generated by Django 5.1.3 on 2024-12-14 14:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toDos', '0017_alter_userrewards_image_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserRewards',
            new_name='UserReward',
        ),
    ]
